### ISSUE TITLE
test_event_code wrong indication

### ISSUE THREAD

**Issue by Loocos** [Setono/MetaConversionsApiBundle#4]
Hi,

Thanks for your amazing plugin.

I just notice when installing it than we've have to add an underscore ( _ ) before the test_event_code, in the readme you say : 
add ?test_event_code=[YOUR_TEST_CODE]
but the correct way is : ?_test_event_code=[YOUR_TEST_CODE]

Is it a mistake ?

**Comment by loevgaard** [comment]
Yes, that's a mistake. Would be nice if you fixed it :)

The corresponding code is here: https://github.com/Setono/MetaConversionsApiBundle/blob/master/src/EventSubscriber/StoreTestEventCodeSubscriber.php#L28

And thank you 👍

**Comment by Loocos** [comment]
Alright, would do it asap :)

**Comment by loevgaard** [comment]
Fixed in #5
