### ISSUE TITLE
How to configure the token?

### ISSUE THREAD

**Issue by adrienlamotte** [Setono/MetaConversionsApiBundle#9]
Hello,

It's the first time I try to use the FB Conversion API, and I'm trying to use your bundle. 
When I read the FB documention, I see that they ask to add the **access_token** to the URL.

How do you configure that token with your bundle?
And is there any other configuration to do?

Thank you!

**Comment by loevgaard** [comment]
You set the `setono_meta_conversions_api.pixels` (https://github.com/Setono/MetaConversionsApiBundle/blob/master/src/DependencyInjection/Configuration.php#L42-L49) setting :)
